# Generated by Django 6.0.3 on 2026-03-22 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(max_length=44, unique=True)),
                ('status', models.CharField(choices=[('WAITING', 'Aguardando envio'), ('PROCESSING', 'Processando'), ('OK', 'Concluído'), ('NOT_FOUND', 'Não encontrado'), ('ERROR', 'Erro')], default='WAITING', max_length=20)),
                ('xml_text', models.TextField(blank=True, null=True)),
                ('pdf_base64', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('mensagem', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
