# Generated by Django 6.0.3 on 2026-03-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfe',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='nfe',
            name='xml_text',
        ),
        migrations.AlterField(
            model_name='nfe',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Aguardando'), ('PROCESSING', 'Processando'), ('OK', 'Pronto'), ('ERROR', 'Erro')], default='WAITING', max_length=20),
        ),
    ]
