# Generated by Django 6.0.3 on 2026-03-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0002_remove_nfe_updated_at_remove_nfe_xml_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfe',
            name='xml_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
