# Generated by Django 6.0.3 on 2026-03-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
