# Generated by Django 6.0.3 on 2026-03-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0006_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='init_point',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
